#!/bin/sh
case "$1" in
-*)
	echo Usage: mkhomedirfor username [...]
	exit 1
	;;
esac
for user in "$@" ; do
	dbus-send --system --dest=com.redhat.oddjob_mkhomedir --print-reply / com.redhat.oddjob_mkhomedir.mkhomedirfor string:"$user"
done
